site_name: Mantis
nav:
  - 'Welcome to Mantis': 'index.md'
  - 'Getting Started':
    - 'Getting Started Guide' : 'gettingstarted/index.md'
    - 'Mantis Concepts': 'gettingstarted/concepts.md'
    - 'Use cases' : 'gettingstarted/usecases.md'
    - 'Explore a Mantis Job locally': 'gettingstarted/local.md'
    - 'Mantis Cluster using Docker': 'gettingstarted/docker.md'
    - 'Mantis Cluster in the cloud': 'gettingstarted/cloud.md'
    - 'Mantis Samples':
        - 'Sine Function': 'gettingstarted/samples/sinesample.md'
        - 'Twitter Sample': 'gettingstarted/samples/twittersample.md'
        - 'Publish to Mantis Sample': 'gettingstarted/samples/publishsample.md'
  - 'Developing with Mantis':
    - 'Publishing Events into Mantis': 'developing/mre.md'
    - 'Writing Mantis Jobs':
      - 'Introduction to Mantis Jobs': 'developing/writingjobs/index.md'
      - 'The Source Component': 'developing/writingjobs/source.md'
      - 'The Processing Stage Component': 'developing/writingjobs/stage.md'
      - 'The Sink Component': 'developing/writingjobs/sink.md'
      - 'Writing Your First Job': 'developing/writingjobs/wordcount.md'
      - 'Writing Your Second Job': 'developing/writingjobs/twitter.md'
      - 'Writing Your Third Job': 'developing/writingjobs/groupby.md'
    - Querying Streams in Mantis:
      - 'Introduction to MQL': 'developing/mql/index.md'
      - 'Operators': 'developing/mql/operators.md'
      - 'Sampling': 'developing/mql/sampling.md'
      - 'Scaling Limits': 'developing/mql/aggregation-scaling-limits.md'
    - The Mantis API:
      - 'API Reference': 'developing/api/index.md'
      - 'Websocket API': 'developing/api/websocket.md'
    - 'The Mantis CLI': 'developing/cli.md'
  - 'Mantis in Production':
    - 'Mantis Job Capacity Planning & Sizing': 'production/capacity.md'
    - 'Mantis Job Autoscaling': 'production/autoscaling.md'
  - Mantis Internals:
      - 'Infrastructure Overview': 'internals/infrastructure.md'
      - 'Mantis Source Jobs': 'internals/sourcejobs.md'
      - 'Mantis Runtime': 'internals/runtime.md'
      - 'Local Development': 'internals/localdockersetup.md'
  - 'Community': 'community.md'
  - 'FAQ': 'faq.md'
  - 'Glossary': 'glossary.md'
theme:
  name: material
  custom_dir: custom_theme/
  favicon: 'images/favicon.ico'
  palette:
    primary: 'blue grey'
    accent: 'indigo'
  logo: 'images/logo.png'
  font-family:
    text: '"Helvetica Neue",Helvetica,Arial,sans-serif'
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/NetflixOSS'
    - icon: fontawesome/brands/github
      link: 'https://netflix.github.io/'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.keys:
      key_map: {"return" : "return",
                "enter" : "return",
                "?" : "?"}
  - pymdownx.superfences
  - pymdownx.snippets
  - def_list
  - extra
extra_css:
  - css/extra.css
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
repo_name: 'Github'
repo_url: 'https://github.com/netflix/mantis'
